In [1]:
import pandas as pd
import numpy as np

In [3]:
student_info = {
    "name": ['amin', 'ali', 'reza', 'amir', "mohsen", "hossein"],
    "age": np.array([20, 23, np.nan, 22, np.nan, 19]),
    "degree": ['BS', 'BS', 'MS', 'MS', "PHD", "BS"],
    "ins": [True, False, True, False, False, False],
    "gpa": [3.5, 3.7, 3.6, 3.8, 3.9, 4]
}
student_info

{'name': ['amin', 'ali', 'reza', 'amir', 'mohsen', 'hossein'],
 'age': array([20., 23., nan, 22., nan, 19.]),
 'degree': ['BS', 'BS', 'MS', 'MS', 'PHD', 'BS'],
 'ins': [True, False, True, False, False, False],
 'gpa': [3.5, 3.7, 3.6, 3.8, 3.9, 4]}

In [7]:
student_df = pd.DataFrame(student_info)
student_df

      name   age degree    ins  gpa
0     amin  20.0     BS   True  3.5
1      ali  23.0     BS  False  3.7
2     reza   NaN     MS   True  3.6
3     amir  22.0     MS  False  3.8
4   mohsen   NaN    PHD  False  3.9
5  hossein  19.0     BS  False  4.0

In [8]:
student_df.head()

     name   age degree    ins  gpa
0    amin  20.0     BS   True  3.5
1     ali  23.0     BS  False  3.7
2    reza   NaN     MS   True  3.6
3    amir  22.0     MS  False  3.8
4  mohsen   NaN    PHD  False  3.9

In [9]:
student_df.head(3)

   name   age degree    ins  gpa
0  amin  20.0     BS   True  3.5
1   ali  23.0     BS  False  3.7
2  reza   NaN     MS   True  3.6

In [10]:
student_df.tail(3)

      name   age degree    ins  gpa
3     amir  22.0     MS  False  3.8
4   mohsen   NaN    PHD  False  3.9
5  hossein  19.0     BS  False  4.0

In [11]:
student_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     4 non-null      float64
 2   degree  6 non-null      object
 3   ins     6 non-null      bool
 4   gpa     6 non-null      float64
dtypes: bool(1), float64(2), object(2)
memory usage: 330.0+ bytes

In [16]:
student_df.loc[[1, 2, 4]]

     name   age degree    ins  gpa
1     ali  23.0     BS  False  3.7
2    reza   NaN     MS   True  3.6
4  mohsen   NaN    PHD  False  3.9